### ISSUE TITLE
Integrate duckduckgo_search as a search backend

### ISSUE THREAD

**Issue by nenkoru** [eryk-mazus/xoxo#1]
It would be nice to have less coupling with a specific search backend, in this case it's Bing and opt for other solutions such as
[duckduckgo_search](https://github.com/deedy5/duckduckgo_search)

**Comment by eryk-mazus** [comment]
Hi! Thanks for the great work. Is there any chance that you could create a smaller pr with only docker and lower version of python required ?

I have slightly different vision regarding the configuration (will add this week probably) relying on yaml.
I tested the pr version of xoxo and chat loop appears to be broken for me

**Comment by nenkoru** [comment]
> Hi! Thanks for the great work. Is there any chance that you could create a smaller pr with only docker and lower version of python required ?
> 
> 
> 
> I have slightly different vision regarding the configuration (will add this week probably) relying on yaml.
> 
> I tested the pr version of xoxo and chat loop appears to be broken for me 

I will separate the PR. I am currently down very deep in a rabiit hole of alpaca(llama) as an inference backend.
Currently working on optimum library to add a support for exporting a model into ONNX format so that optimizations could be taken to make fast inferences.

**Comment by eryk-mazus** [comment]
Hi,

I've ended up droping bing search completly and just relaced it with duckduckgo
