### ISSUE TITLE
Integrate llama as a LLM backend for API-less inference of search results

### ISSUE THREAD

**Issue by nenkoru** [eryk-mazus/xoxo#2]
Basically the whole idea in the title.
Currently the project heavily relies on OpenAI completion API.

It would be great to integrate with something like:
[llama.cpp](https://github.com/ggerganov/llama.cpp)
[llama-rs](https://github.com/setzer22/llama-rs)
[pyllama](https://github.com/juncongmoo/pyllama)

This way the inference could be done locally without a reliance on 3rd party services

**Comment by nenkoru** [comment]
Indeed the first two need to have python wrapper around them, but the third one could be integrated pretty easily.
I believe dependency injection technique would be quite suitable here.

**Comment by nenkoru** [comment]
After an investigation and creating a small wrapper around llama.cpp it turns out that I can't get it to response with a NEXT COMMAND normally. I guess training of a model is needed, or more examples within a prompt.

Link to reproduce test env:
https://gist.github.com/nenkoru/ebf99934fbd7935735901d5ab6cf5da1

To reproduce that you need to have a compiled version of llama.cpp and weights for LLAMA model

**Comment by eryk-mazus** [comment]
Thank you for the tremendous work. My guess is that indeed out of the box LLaMA will perform poorly (especially the smaller models). More promising direction is to use the alpaca (instruction-tuned llama):
* https://github.com/tatsu-lab/stanford_alpaca

I will investigate this
